### ISSUE TITLE
Used ‘refresh icons’ and now most of the apps are gone 

### ISSUE THREAD

**Issue by addiosamigo38** [joedefen/crostini-kde-setup#2]
I had just installed ‘Geary’ using the ‘discover’ app and I noticed it was a penguin icon. I opened ‘maintgui’ and chose ‘refresh icons’ and all the apps in my Linux folder have all gone except terminal and only office.

**Comment by joedefen** [comment]
Is this a permanent condition?  They should reappear in the Linux folder in a bit.  In the worst case, restarting the container, but that should not be required.   The mechanisms for getting/displaying the correct icon seem imperfect, but mostly they work for me w/o using the button.  You need to have a low bar for success, I think.  Anyhow, if the icons did not recover for you as they do always for me, let me know that.  Also, if the there were any apparent errors shown in the panel under the buttons, share that with me.  I've never seen any, but maybe your experience something?

Oh yeah, I'll add something to the README about the icons temporarily disappearing as part of the "refresh".

**Comment by addiosamigo38** [comment]
Thanks for the prompt reply. I waited a few mins and they were still not there, I rebooted and they still did not appear. When you say they always come back after a bit, how long are we taking? Is there a way to run maintgui without the icon? Cheers

**Comment by joedefen** [comment]
Nominally, it takes 30s to 60s for them to restart.  Never seen the permanent condition you speak of.  When "Refresh Icons" runs, it looks like this: 
```
+ sudo mv /usr/share/applications /usr/share/applications.tmp
+ sudo mv /home/joedef/.local/share/applications /home/joedef/.local/share/applications.tmp
+ sleep 5
+ sudo mv /usr/share/applications.tmp /usr/share/applications
+ sudo mv /home/joedef/.local/share/applications.tmp /home/joedef/.local/share/applications
```
As you can see, there are two directories for icons, and they are moved to a similarly named .tmp directory then back.  Are the .tmp directories there?  Are the non-.tmp directories there? Are the directories empty?  If the .tmp directories are then, run the last two commands as shown to restore them manually to the right place.

Did you perhaps exit MaintGUI before it finished the operation?  There is a 5 second window where that is possible. Generally, you must wait until you see the line: `---------- DONE --------------` before you exit MaintGUI?  If you did that, the .tmp directories need to be moved back.  I'll add "wait for DONE" to the instructions, even if that was not the cause.

If you can find the .desktop file (in a .tmp directory or wherever), you run it with `gtk-launch {path-to-the-desktop-file}`.  For MaintGUI in particular, you can run `~/crostini-kde-setup/maint-gui` directly w/o the .desktop file.

**Comment by addiosamigo38** [comment]
So I opened the Chromebook this morning, and left it while I got ready and they reappeared, apart from geary. I can run geary from the discover app though. Maybe I was just inpatient? Thanks for your help though! Is there any logs I can check to see what happened?

**Comment by joedefen** [comment]
"Patient" is a minute or two, not all night.
- If you closed MaintGUI mid-operation, then it would not have repaired itself ever, I think.
- If you did not close MaintGUI mid-operation, then it should have completely repaired itself and losing one launcher makes no sense.

The only diagnostic that I can think of is, from Terminal, run:
- `ls /usr/share/applications* ~/.local/share/applications*`

That will show all the .desktop files in their right folder and in the .tmp folder, and provide all the clues available. Share that, if it is interesting.  Re geany:

- from the Terminal, you can run `geany &` to launch if that easier
- but  unless its .desktop file is restored some other way, I'd just uninstall/re-install geany
- for me, I've never noticed geany having any other icon than its silly yellow magic lamp

**Comment by joedefen** [comment]
Just to tidy up, I'm closing this issue.  I suspect that you closed MaintGUI although (1) you have no recall of that and (2) the icons returning the next day is inexplicable/contradictory.   But, from day one, I realized that closing MaintGUI mid-operation was a vulnerability. Anyhow, I found a way to block unforced closes (i.e., hitting X on the title bar), and added an EXIT button that only works when idle; i.e., this discussion triggered me to fix that festering vulnerability whether it was the root cause of the problem or not.

**Comment by addiosamigo38** [comment]
I did it again yesterday and noticed the ‘finished’ status. My icons took a while to come back but they did this time.
I think I didn’t understand the process properly at first and panicked and then restarted, then I left it to go to bed and they were back in the morning, the probably came back before the morning , I just wouldn’t of noticed. 
Thanks for your help!
